#!/usr/bin/env bash

# patterns that match no files expand to a null string
shopt -s nullglob

exitcode=0
for f in "$GRADER"/*.mli; do
    base=$(basename "$f")
    if [ ! -f "$SUBMISSION_DIR/$base" ] || ! cmp -s "$f" "$SUBMISSION_DIR/$base"; then
        exitcode=1
        echo "> Detected changes to $base! Please restore this file."
    fi
done

exit $exitcode
